# Generated by Django 2.1 on 2020-07-02 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('home_name', models.CharField(max_length=128, null=True)),
                ('number', models.CharField(max_length=24, null=True)),
                ('will_done', models.DateField(null=True)),
                ('block_oid', models.CharField(default='', max_length=32, primary_key=True, serialize=False, unique=True)),
                ('will_done_string', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64, null=True)),
                ('title', models.CharField(max_length=64, null=True)),
                ('sort_order', models.IntegerField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('sort_order', models.IntegerField(null=True, unique=True)),
                ('name', models.CharField(max_length=128, null=True, unique=True)),
                ('page_url', models.CharField(max_length=128, null=True, unique=True)),
                ('developer', models.CharField(max_length=64, null=True)),
                ('tag_list', models.CharField(max_length=256, null=True)),
                ('address', models.CharField(max_length=256, null=True)),
                ('district', models.CharField(max_length=128, null=True)),
                ('metro', models.CharField(max_length=64, null=True)),
                ('metro_distance', models.CharField(max_length=5, null=True)),
                ('wall_type', models.CharField(max_length=16, null=True)),
                ('trim', models.CharField(max_length=16, null=True)),
                ('agreement', models.CharField(max_length=16, null=True)),
                ('description', models.CharField(max_length=10000, null=True)),
                ('wall_type_string', models.CharField(max_length=128, null=True)),
                ('metro_distance_string', models.CharField(max_length=32, null=True)),
                ('sort_metro_distance', models.IntegerField(null=True)),
                ('metro_line', models.CharField(max_length=1024, null=True)),
                ('preview_285', models.CharField(max_length=1024, null=True)),
                ('preview_531', models.CharField(max_length=1024, null=True)),
                ('delivery_part', models.CharField(max_length=32, null=True)),
                ('delivery_month', models.CharField(max_length=32, null=True)),
                ('will_done_min', models.DateField(null=True)),
                ('plans_count', models.CharField(max_length=20, null=True)),
                ('blocks_count', models.CharField(max_length=20, null=True)),
                ('trim_full', models.CharField(max_length=256, null=True)),
                ('trim_short', models.CharField(max_length=256, null=True)),
                ('payment', models.CharField(max_length=1024, null=True)),
                ('banks', models.CharField(max_length=1024, null=True)),
                ('min_price', models.IntegerField(null=True)),
                ('max_price', models.IntegerField(null=True)),
                ('price_set', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=128, null=True)),
                ('form_name', models.CharField(max_length=64, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetroLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('color', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='MetroStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.MetroLine')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_number', models.IntegerField(null=True)),
                ('full', models.CharField(max_length=1024, null=True)),
                ('resize', models.CharField(max_length=1024, null=True)),
                ('preview_285', models.CharField(max_length=1024, null=True)),
                ('preview_531', models.CharField(max_length=1024, null=True)),
                ('home', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Home')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_name', models.CharField(max_length=128, null=True)),
                ('block_number', models.CharField(max_length=24, null=True)),
                ('rooms', models.CharField(max_length=10, null=True)),
                ('square_total', models.FloatField(null=True)),
                ('square_kitchen', models.FloatField(null=True)),
                ('trim', models.CharField(max_length=16, null=True)),
                ('agreement', models.CharField(max_length=32, null=True)),
                ('payment', models.CharField(max_length=64, null=True)),
                ('banks', models.TextField(max_length=1024, null=True)),
                ('roof_height', models.CharField(max_length=20, null=True)),
                ('base_price', models.IntegerField(null=True)),
                ('discount_price', models.IntegerField(null=True)),
                ('floor', models.CharField(max_length=20, null=True)),
                ('plan_img_url', models.CharField(max_length=256, null=True)),
                ('trim_full', models.CharField(max_length=128, null=True)),
                ('trim_short', models.CharField(max_length=128, null=True)),
                ('rooms_full', models.CharField(max_length=32, null=True)),
                ('rooms_short', models.CharField(max_length=32, null=True)),
                ('floor_number', models.IntegerField(null=True)),
                ('floor_count', models.IntegerField(null=True)),
                ('will_done_month', models.CharField(max_length=128, null=True)),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Block')),
                ('home', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Home')),
            ],
        ),
        migrations.CreateModel(
            name='ShortPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.CharField(max_length=10, null=True)),
                ('price_from', models.IntegerField(null=True)),
                ('price_to', models.IntegerField(null=True)),
                ('square_from', models.FloatField(null=True)),
                ('square_to', models.FloatField(null=True)),
                ('rooms_string', models.CharField(max_length=32, null=True)),
                ('short_price_from', models.FloatField(null=True)),
                ('short_price_to', models.FloatField(null=True)),
                ('home', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Home')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=64, null=True)),
                ('title', models.CharField(max_length=64, null=True)),
                ('mark', models.BooleanField(null=True)),
                ('sort_order', models.IntegerField(null=True, unique=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Category')),
                ('homes', models.ManyToManyField(to='core.Home')),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Home'),
        ),
    ]
